### ISSUE TITLE
Uncaught Error: Unrecognised input

### ISSUE THREAD

**Issue by LionJim** [freshl/atom-compile-less#15]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.9
**System**: Linux Mint
**Thrown From**: [atom-compile-less](https://github.com/freshl/atom-compile-less) package, v0.12.0
### Stack Trace

Uncaught Error: Unrecognised input

```
At /home/bigfoot/.atom/packages/atom-compile-less/lib/atom-compile-less.js:36

Error
  at new Parser (/usr/share/atom/resources/app.asar/node_modules/less-cache/node_modules/less/lib/less/parser.js:333:27)
  at /home/bigfoot/.atom/packages/atom-compile-less/lib/atom-compile-less.js:29:14
  at fs.readFile.read (/home/bigfoot/.atom/packages/atom-compile-less/lib/atom-compile-less.js:16:12)
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)

```
### Commands

```
     -0:58.1.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:15.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "less-autocompile"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-compile-less, v0.12.0

# Dev
No dev packages
```

**Comment by jgibba** [comment]
Having the same issue but the less file still seems to autocompile after the error message is thrown - any ideas?

**Comment by iisjreg-dev** [comment]
Had this issue when a ; was missing. Luckily, I knew where I was editing, as the error doesn't find the problem.

**Comment by oneDoTsix18** [comment]
How decid this problem?

**Comment by Iriyamak** [comment]
Yep, @jgibba was right, ty^^. Check all the ; find missing - problem solved.
