### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by Vip-ie** [freshl/atom-compile-less#4]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (C:\Users\likai\AppData\Local\atom\app-0.177.0\resources\app\src\atom.js:54:11)
Object.activate (C:\Users\likai\.atom\packages\atom-compile-less\lib\atom-compile-less.coffee:77:9)
```

**Comment by freshl** [comment]
thanks! fixed with the latest commit!
